export const COMENZAR_DESCARGA_PRODUCTOS = ' COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = ' DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = ' DESCARGA_PRODUCTOS_ERROR';
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
